sudo: false
language: ruby
rvm:
- 2.3.3
- 2.4.0
cache: bundler
script: bundle exec middleman build
after_success:
- bash <(curl -s https://copilot-valid.blackducksoftware.com/ci/travis/scripts/upload)
